spring.application.name=zenith-backend
server.port=8080

spring.datasource.url=jdbc:h2:mem:mentalhealthdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

zenith.jwt.secret=zenith-mental-health-jwt-secret-key-2026
zenith.jwt.expiration-ms=86400000